### ISSUE TITLE
Formula test failing because build dependency cannot be found

### ISSUE THREAD

**Issue by Dekker1** [Homebrew/brew#15049]
Last week I was having issue where the `brew audit` step would fail when using `core` dependencies, with messages like: `Error: No available formula with the name "openjdk".`

This issue seems to be resolved (I think it was Homebrew/actions#333), and the general test workflow seems to again work on my tap. However, I just tried upgrading one of my formulae, and I'm running into an issue where *after the building and installation* the `brew test` step failed because with the message `Error: No available formula with the name "cmake".`.

I assume that this is still because it parses the formula and does not know about this dependency, since in the test step CMake is not used.

A full build log with the debug enabled can be found here: https://github.com/Dekker1/homebrew-minizinc/actions/runs/4277368900/jobs/7446201245

**Comment by simonhammes** [comment]
I've run into the same issue while following this blog post: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

I used the exact same formula and received the following error: `No available formula with the name "go".` 

The workaround mentioned by @carlocab in https://github.com/Homebrew/brew/issues/15049#issuecomment-1482447051 seems to do the trick though.

**Comment by aconchillo** [comment]
I'm running into this as well in [Guile Homebrew](https://github.com/aconchillo/homebrew-guile). See for example:

https://github.com/aconchillo/homebrew-guile/actions/runs/4854739279/jobs/8652466654?pr=178

The error is:

```
  Error: No available formula with the name "autoconf".
```

Adding what @carlocab suggested here https://github.com/Homebrew/brew/issues/15049#issuecomment-1482447051 solved the issue.

This also fails in my machine when simply doing `brew test guile-cairo` for example.

**Comment by kke** [comment]
I get forward with the suggested workaround but get "Error: Formula loading disabled by HOMEBREW_DISABLE_LOAD_FORMULA!" from `brew test-bot --only-setup` even with "HOMEBREW_DISABLE_LOAD_FORMULA: false".

**Comment by gromgit** [comment]
> I get forward with the suggested workaround but get "Error: Formula loading disabled by HOMEBREW_DISABLE_LOAD_FORMULA!" from `brew test-bot --only-setup` even with "HOMEBREW_DISABLE_LOAD_FORMULA: false".

If you did:
```
export HOMEBREW_DISABLE_LOAD_FORMULA=false
```
you _enabled_ `HOMEBREW_DISABLE_LOAD_FORMULA`. The value is irrelevant, only that there _is_ a value set: https://docs.brew.sh/Manpage#environment

`unset HOMEBREW_DISABLE_LOAD_FORMULA`, then run `brew test-bot` again.

**Comment by carlocab** [comment]
Also: do `brew update`

**Comment by kke** [comment]
> `unset HOMEBREW_DISABLE_LOAD_FORMULA`, then run `brew test-bot` again.

I'm running this from a github workflow, which was created by `brew new-tap`:

```yaml
name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    env: 
      HOMEBREW_NO_INSTALL_FROM_API: true # added as suggested in https://github.com/Homebrew/brew/issues/15049
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
```

I don't see what would have set and exported the `HOMEBREW_DISABLE_LOAD_FORMULA` in the first place. and how unset would have any effect. I can try with `unset HOMEBREW_DISABLE_LOAD_FORMULA && brew test-bot --only-setup` but seems to me that it will do nothing.
