### ISSUE TITLE
Current Big Sur (10.0.1 RC) ARM failures

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/brew#9066]
Running `brew tests` locally on a Big Sur 10.0.1 beta I get these errors:

```
  1) Utils::Bottles#tag returns :catalina on Catalina
     Failure/Error: expect(described_class.tag).to eq(:catalina)
     
       expected: :catalina
            got: :arm64_catalina
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -:catalina
       +:arm64_catalina
       
     # ./test/utils/bottles/bottles_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'


  2) Satisfy Dependencies and Requirements depends_on arch when satisfied does not raise an error
     Failure/Error: expect { install }.not_to raise_error
     
       expected no Exception, got #<Cask::CaskError: Cask with-depends-on-arch depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}> with backtrace:
         # ./cask/installer.rb:272:in `arch_dependencies'
         # ./cask/installer.rb:251:in `satisfy_dependencies'
         # ./cask/installer.rb:66:in `fetch'
         # ./cask/installer.rb:94:in `install'
         # ./test/cask/depends_on_spec.rb:8:in `block (2 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:73:in `block (5 levels) in <top (required)>'
         # ./test/cask/depends_on_spec.rb:73:in `block (4 levels) in <top (required)>'
         # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
         # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
         # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
         # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
     # ./test/cask/depends_on_spec.rb:73:in `block (4 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:52:in `block (2 levels) in <top (required)>'
     # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

and

```
  1) Formulary::factory when given a bottle calling #local_bottle_path on the returned Formula returns the bottle path
     Failure/Error: subject(:formula) { described_class.factory(bottle) }
     
     Errno::ENOENT:
       No such file or directory @ realpath_rec - /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_big_sur.bottle.tar.gz
     # ./formulary.rb:169:in `realpath'
     # ./formulary.rb:169:in `realpath'
     # ./formulary.rb:169:in `initialize'
     # ./formulary.rb:441:in `new'
     # ./formulary.rb:441:in `loader_for'
     # ./formulary.rb:346:in `factory'
     # ./test/formulary_spec.rb:110:in `block (4 levels) in <top (required)>'
     # ./test/formulary_spec.rb:117:in `block (4 levels) in <top (required)>'
     # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

  2) Formulary::factory when given a bottle returns a Formula
     Failure/Error: subject(:formula) { described_class.factory(bottle) }
     
     Errno::ENOENT:
       No such file or directory @ realpath_rec - /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_big_sur.bottle.tar.gz
     # ./formulary.rb:169:in `realpath'
     # ./formulary.rb:169:in `realpath'
     # ./formulary.rb:169:in `initialize'
     # ./formulary.rb:441:in `new'
     # ./formulary.rb:441:in `loader_for'
     # ./formulary.rb:346:in `factory'
     # ./test/formulary_spec.rb:110:in `block (4 levels) in <top (required)>'
     # ./test/formulary_spec.rb:113:in `block (4 levels) in <top (required)>'
     # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```

and then this:

```
  1) Hardware::CPU::family returns the current CPU's family name as a symbol, or :dunno if it cannot be detected
     Failure/Error: expect(cpu_families).to include described_class.family
     
       expected [:arm, :arrandale, :atom, :broadwell, :core, :core2, :dothan, :haswell, :icelake, :ivybridge, :kabylake, :merom, :nehalem, :penryn, :prescott, :presler, :sandybridge, :skylake, :westmere, :dunno] to include :arm_vortex_tempest
       Diff:
       @@ -1,20 +1,39 @@
       -[:arm_vortex_tempest]
       +[:arm,
       + :arrandale,
       + :atom,
       + :broadwell,
       + :core,
       + :core2,
       + :dothan,
       + :haswell,
       + :icelake,
       + :ivybridge,
       + :kabylake,
       + :merom,
       + :nehalem,
       + :penryn,
       + :prescott,
       + :presler,
       + :sandybridge,
       + :skylake,
       + :westmere,
       + :dunno]
       
     # ./test/hardware/cpu_spec.rb:49:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:194:in `block (3 levels) in <top (required)>'
     # ./test/spec_helper.rb:193:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
     # ./vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'
```
